blueprint:
  name: "Dimmer por Modo + Reversão por Inatividade [ZG-101Z_D_1 (Z2M)]"
  description: >
    Controla luz e switch a com ZG-101Z_D_1 via Zigbee2MQTT.
    Actions: single, double, hold, rotate_left/right.
    Inclui:
    • Reversão automática após X segundos sem ações
    • Reset do modo para Brilho quando a luz desliga
    • Modo Cor: primeira alteração força brilho a 100%
    • Modo Temperatura: incremento calculado manualmente (mireds)
  domain: automation

  input:
    topic_action:
      name: "Tópico MQTT (action)"
      description: "Ex.: zigbee2mqtt/Dimmer Quarto Rafaela/action"
      selector:
        text: {}

    luz:
      name: "Luz a controlar"
      selector:
        entity:
          domain: light

    tv:
      name: "TV / Switch a controlar (para hold)"
      selector:
        entity:
          domain: switch

    modo:
      name: "Input Select do modo"
      selector:
        entity:
          domain: input_select

    rotulo_brilho:
      name: "Rótulo — Brilho"
      default: "Brilho"
      selector:
        text: {}

    rotulo_cor:
      name: "Rótulo — Cor"
      default: "Cor"
      selector:
        text: {}

    rotulo_temp:
      name: "Rótulo — Temperatura"
      default: "Temperatura"
      selector:
        text: {}

    passo_brilho:
      name: "Incremento brilho (%)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1

    passo_cor:
      name: "Incremento cor (Hue graus)"
      default: 20
      selector:
        number:
          min: 1
          max: 90
          step: 1

    passo_temp:
      name: "Incremento temperatura (mireds)"
      default: 50
      selector:
        number:
          min: 5
          max: 200
          step: 5

    segundos_reverter:
      name: "Timeout para reverter para Brilho"
      default: 30
      selector:
        number:
          min: 5
          max: 600
          step: 5

mode: restart

trigger:
  - platform: mqtt
    topic: !input topic_action
    id: "z2m_action"

  # Trigger adicional → quando luz desliga, forçar modo Brilho
  - platform: state
    entity_id: !input luz
    to: "off"
    id: "luz_desligou"

variables:
  luz: !input luz
  tv: !input tv
  modo: !input modo
  rotulo_brilho: !input rotulo_brilho
  rotulo_cor: !input rotulo_cor
  rotulo_temp: !input rotulo_temp
  passo_brilho: !input passo_brilho
  passo_cor: !input passo_cor
  passo_temp: !input passo_temp
  segundos_reverter: !input segundos_reverter
  acao: "{{ trigger.payload | default('', true) | lower }}"

action:
  - choose:

      # ---------------------------
      # 1) Luz desligou → reset modo
      # ---------------------------
      - conditions: "{{ trigger.id == 'luz_desligou' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: "{{ modo }}"
            data:
              option: "{{ rotulo_brilho }}"

      # ---------------------------
      # 2) Ações Z2M
      # ---------------------------
      - conditions: "{{ trigger.id == 'z2m_action' }}"
        sequence:

          - choose:

              # single → toggle luz
              - conditions: "{{ acao == 'single' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ luz }}"

              # double → próximo modo
              - conditions: "{{ acao == 'double' }}"
                sequence:
                  - service: input_select.select_next
                    target:
                      entity_id: "{{ modo }}"

              # hold → toggle TV
              - conditions: "{{ acao == 'hold' }}"
                sequence:
                  - service: switch.toggle
                    target:
                      entity_id: "{{ tv }}"

              # rotate
              - conditions: "{{ acao in ['rotate_left','rotate_right'] }}"
                sequence:
                  - choose:

                      # ------------------------------
                      # MODO BRILHO
                      # ------------------------------
                      - conditions: "{{ states(modo) == rotulo_brilho }}"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: "{{ luz }}"
                            data:
                              brightness_step_pct: >
                                {% if acao == 'rotate_right' %}
                                  {{ passo_brilho }}
                                {% else %}
                                  {{ -passo_brilho }}
                                {% endif %}

                      # ------------------------------
                      # MODO TEMPERATURA — mireds manual
                      # ------------------------------
                      - conditions: "{{ states(modo) == rotulo_temp }}"
                        sequence:
                          - variables:
                              mired_atual: >
                                {{ state_attr(luz,'color_temp') 
                                   | default(300) }}
                              mired_novo: >
                                {% set minv = 153 %}
                                {% set maxv = 500 %}
                                {% if acao == 'rotate_right' %}
                                  {% set v = mired_atual - passo_temp %}
                                {% else %}
                                  {% set v = mired_atual + passo_temp %}
                                {% endif %}
                                {{ [maxv, [minv, v]|max]|min }}
                          - service: light.turn_on
                            target:
                              entity_id: "{{ luz }}"
                            data:
                              color_temp: "{{ mired_novo }}"

                      # ------------------------------
                      # MODO COR — primeiro toque → brilho = 100%
                      # ------------------------------
                      - conditions: "{{ states(modo) == rotulo_cor }}"
                        sequence:
                          - variables:
                              hue_atual: "{{ state_attr(luz,'hs_color')[0] | default(0) }}"
                              sat_atual: 100
                              brilho_atual: "{{ state_attr(luz,'brightness') | default(255) }}"
                              forcar_brilho: "{{ brilho_atual < 250 or states(luz)=='off' }}"
                              hue_novo: >
                                {% if acao == 'rotate_right' %}
                                  {{ (hue_atual + passo_cor) % 360 }}
                                {% else %}
                                  {{ (hue_atual - passo_cor) % 360 }}
                                {% endif %}

                          # Se for o primeiro movimento → brilho = 100%
                          - if: "{{ forcar_brilho }}"
                            then:
                              - service: light.turn_on
                                target:
                                  entity_id: "{{ luz }}"
                                data:
                                  brightness: 255

                          # Agora altera HUE
                          - service: light.turn_on
                            target:
                              entity_id: "{{ luz }}"
                            data:
                              hs_color:
                                - "{{ hue_novo }}"
                                - "{{ sat_atual }}"

          # ----------------------------------------------
          # Reversão automática para modo "Brilho"
          # ----------------------------------------------
          - if: "{{ states(modo) != rotulo_brilho }}"
            then:
              - wait_for_trigger:
                  - platform: mqtt
                    topic: !input topic_action
                timeout: >
                  {% set s = segundos_reverter|int %}
                  {{ '%02d:%02d:%02d'|format(s//3600,(s%3600)//60,s%60) }}
                continue_on_timeout: true

              - if: "{{ not wait.completed and states(modo) != rotulo_brilho }}"
                then:
                  - service: input_select.select_option
                    target:
                      entity_id: "{{ modo }}"
                    data:
                      option: "{{ rotulo_brilho }}"
